import type { Program, Settings } from './types'

/**
 * The default 4-day program (Push / Pull / Legs / Upper), ported verbatim from
 * the original single-file app. This is only a *seed*: once loaded it lives in
 * persisted state and can be edited freely in the UI (see the Program editor).
 * Estonian copy is preserved intentionally.
 */
export const DEFAULT_PROGRAM: Program = {
  days: [
    {
      key: 'push',
      name: 'Push — Rind, Õlad, Triitseps',
      sub: '4 harjutust · ~45–50 min',
      exercises: [
        {
          id: 'kang_press',
          name: 'Kangiga lamades rinnalt surumine',
          note: 'Põhiliigutus — seo kõhulihased, kontrollitud tempo',
          sets: 4,
          repsLow: 6,
          repsHigh: 8,
          weightStart: 40,
          weightStep: 2.5,
          hasWeight: true,
        },
        {
          id: 'rinna_masin',
          name: 'Rinna masin',
          note: 'Kontrollitud surumine, pigista tipus 1 sek',
          sets: 3,
          repsLow: 8,
          repsHigh: 10,
          weightStart: 40,
          weightStep: 5,
          hasWeight: true,
        },
        {
          id: 'ohp',
          name: 'Õlapress hantlitega (istudes)',
          note: 'Sirge selg, küünarnukid 90° all',
          sets: 3,
          repsLow: 8,
          repsHigh: 10,
          weightStart: 12.5,
          weightStep: 2.5,
          hasWeight: true,
        },
        {
          id: 'triits_masin',
          name: 'Triitseps masin (ette kallutades)',
          note: 'Küünarnukid fikseeritud, suru lõpuni alla',
          sets: 3,
          repsLow: 10,
          repsHigh: 12,
          weightStart: 80,
          weightStep: 5,
          hasWeight: true,
        },
      ],
    },
    {
      key: 'pull',
      name: 'Pull — Selg, Bitseps',
      sub: '4 harjutust · ~45–50 min',
      exercises: [
        {
          id: 'maatombe',
          name: 'Rumäniamaatõmme (kangiga)',
          note: 'Selg sirge, tunne venitust tagareies — töötab ka tuharal!',
          sets: 4,
          repsLow: 6,
          repsHigh: 8,
          weightStart: 40,
          weightStep: 5,
          hasWeight: true,
        },
        {
          id: 'lai_haare',
          name: 'Lai haare plokis (lat pulldown)',
          note: 'Tõmba rinnale, küünarnukid alla-taha, ära kiigu',
          sets: 3,
          repsLow: 8,
          repsHigh: 10,
          weightStart: 45,
          weightStep: 5,
          hasWeight: true,
        },
        {
          id: 'selg_masin',
          name: 'Masinal seljtõmme (seated row)',
          note: 'Pigista abaluud kokku lõppasendis, hoia 1 sek',
          sets: 3,
          repsLow: 10,
          repsHigh: 12,
          weightStart: 35,
          weightStep: 5,
          hasWeight: true,
        },
        {
          id: 'bitseps',
          name: 'Bitseps — hantliga käärltõmme',
          note: 'Küünarnukid fikseeritud keha kõrval, puhas liigutus',
          sets: 3,
          repsLow: 8,
          repsHigh: 10,
          weightStart: 15,
          weightStep: 2.5,
          hasWeight: true,
        },
      ],
    },
    {
      key: 'jalad',
      name: 'Jalad — Tuhar fookusega',
      sub: '5 harjutust · ~50 min · tuhar = prioriteet',
      exercises: [
        {
          id: 'hip_thrust',
          name: 'Hip thrust (kangiga)',
          note: '🍑 Nr 1 tuharaharjutus — puusad üles, pigista tipus täielikult',
          sets: 4,
          repsLow: 8,
          repsHigh: 10,
          weightStart: 40,
          weightStep: 5,
          hasWeight: true,
        },
        {
          id: 'bulgaaria',
          name: 'Bulgaaria split squat (hantliga)',
          note: '🍑 Tagumine jalg pingil — tuhar töötab rohkem kui tavakükkis',
          sets: 3,
          repsLow: 8,
          repsHigh: 10,
          weightStart: 10,
          weightStep: 2.5,
          hasWeight: true,
        },
        {
          id: 'leg_press',
          name: 'Leg press',
          note: 'Jalad kõrgemal plaadil = rohkem tuhart. Täisamplituud.',
          sets: 3,
          repsLow: 10,
          repsHigh: 12,
          weightStart: 80,
          weightStep: 5,
          hasWeight: true,
        },
        {
          id: 'tagareis',
          name: 'Tagareis kõhuli (leg curl)',
          note: 'Tahapoole reie — tasakaalustab quad/hamstring jõudu',
          sets: 3,
          repsLow: 10,
          repsHigh: 12,
          weightStart: 35,
          weightStep: 2.5,
          hasWeight: true,
        },
        {
          id: 'saared',
          name: 'Säär masinal',
          note: 'Täisamplituud — hoia tipus 1 sek, lase alla aeglaselt',
          sets: 3,
          repsLow: 12,
          repsHigh: 15,
          weightStart: 20,
          weightStep: 5,
          hasWeight: true,
        },
      ],
    },
    {
      key: 'upper',
      name: 'Ülakeha — Kõik ülaosa',
      sub: '5 harjutust · ~50 min · kordab kõike teise nurgalt',
      exercises: [
        {
          id: 'kald_press',
          name: 'Kaldpingil hantlpress (30°)',
          note: 'Rõhk ülarinnale — erinev nurk kui päev 1',
          sets: 3,
          repsLow: 8,
          repsHigh: 10,
          weightStart: 15,
          weightStep: 2.5,
          hasWeight: true,
        },
        {
          id: 'pullup',
          name: 'Lairiputõmme / assisted pullup',
          note: 'Täisamplituud — kui saad >10, lisa raskusvöö',
          sets: 3,
          repsLow: 6,
          repsHigh: 10,
          weightStart: 0,
          weightStep: 2.5,
          hasWeight: false,
        },
        {
          id: 'ohp_upper',
          name: 'Seisul õlapress (kangiga / smith)',
          note: 'Kang rinnal, suru otse üles — suurim õlaharjutus',
          sets: 3,
          repsLow: 8,
          repsHigh: 10,
          weightStart: 10,
          weightStep: 2.5,
          hasWeight: true,
        },
        {
          id: 'bitseps_upper',
          name: 'Bitseps kaldpingil hantliga',
          note: 'Istu 45° kaldpingil — täielik venitus all, max kasv',
          sets: 3,
          repsLow: 8,
          repsHigh: 10,
          weightStart: 12.5,
          weightStep: 2.5,
          hasWeight: true,
        },
        {
          id: 'triits_upper',
          name: 'Triitseps kaabliga üle pea',
          note: 'Küünarnukid kõrvade kõrval fikseeritud',
          sets: 3,
          repsLow: 10,
          repsHigh: 12,
          weightStart: 15,
          weightStep: 2.5,
          hasWeight: true,
        },
      ],
    },
  ],
}

/** Default user settings. */
export const DEFAULT_SETTINGS: Settings = {
  deloadAfterStalls: 3,
  deloadFactor: 0.1,
  deloadEveryWeeks: 0,
}
